name: Action for Node.js
description: Node.js setup cache

inputs:
  node-version:
    description: Node.js version
    required: false
    default: 16.x

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Restore node_modules from cache
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules/
          !**/node_modules/.cache
        key: modules-cache__nodejs-${{ inputs.node-version }}__${{ hashfiles('**/package-lock.json') }}

    - name: Restore from cache of builds
      id: build-cache
      if: steps.cache-node-modules.outputs.cache-hit == 'true'
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules/.cache
        key: builds-cache-hash__${{ hashFiles('**/package-lock.json') }}-${{ github.ref }}
        restore-keys: builds-cache__nodejs-${{ inputs.node-version }}__${{ hashFiles('**/package-lock.json') }}

    - name: Restore from global NPM cache
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-cache__nodejs-${{ inputs.node-version }}__${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-cache-hash__

    - shell: bash
      run: |
        echo "Show environment Node.js, npm ..."
        node -v
        npm -v

    - shell: bash
      run: |
        echo "Provide global variables ..."
        echo "NPM_CONFIG_CACHE=~/.npm" >> $GITHUB_ENV
        echo "NODE_OPTIONS=--max-old-space-size=12288" >> $GITHUB_ENV
        echo "CYPRESS_CACHE_FOLDER=node_modules/cache-cypress" >> $GITHUB_ENV

    - name: Clean install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
