name: CI

env:
  node_version: 16.x

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node_version}}
          cache: npm

      - name: Install
        run: npm ci
      - name: Test_Jungle_UI
        run: npm run test-coverage:jungle-ui
      - name: Build_Jungle_UI
        run: npm run build-jungle-ui
      - name: Build_UI
        run: npm run build-ui
      - name: Test_UI
        run: npm run test-coverage:ui

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}



