name: CI

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v2

      - name: Build Affected Apps
        run: npm run affected:build --base=${{ env.NX_BASE }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v2

      - name: Test Affected Apps
        run: npm run affected:test:coverage --base=${{ env.NX_BASE }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Derive appropriate SHAs for base and head for nx affected commands
        uses: nrwl/nx-set-shas@v2

      - name: Lint Affected Apps
        run: npm run affected:lint --base=${{ env.NX_BASE }}

