name: CI

env:
  node_version: 16.x

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node_version}}
          cache: npm

      - name: Install
        run: npm i
      - name: Build
        run: npm run build



