name: CI

env:
  node_version: 16.x

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.node_version}}
          cache: npm

      - name: Install Project Dependencies
        run: npm ci

      - name: Test Jungle-UI
        run: npm run test-coverage:jungle-ui

      - name: Build Jungle-UI
        run: npm run build:jungle-ui

      - name: Test UI
        run: npm run test-coverage:ui

      - name: Build UI
        run: npm run build:ui

      - name: SonarCloud Scan UI
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/apps/ui/lcov.info
            -Dsonar.typescript.tsconfigPath=apps/ui/tsconfig.app.json
            -Dsonar.sources=apps/ui/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan Jungle-UI
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/libs/jungle-ui/lcov.info
            -Dsonar.typescript.tsconfigPath=libs/jungle-ui/tsconfig.lib.json
            -Dsonar.sources=libs/jungle-ui/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


