name: release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: release type
        required: true
        default: 'minor'
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "vddastranger"

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Bump version and build
        run: npm run pre-publish:${{ github.event.inputs.mode }}

      - name: Publish package
        run: npm run publish:jungle-ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Git push
        run: |
          git add .
          git commit -m 'release: new ${{ github.event.inputs.mode }} library version' --no-verify

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          title: 'Release/${{ github.event.inputs.mode }}'
          delete-branch: true

      - name: Build Storybook
        run: npm run build:storybook:jungle-ui

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/storybook # The folder the action should deploy.
#      - name: Build changelog
#        id: build_changelog
#        uses: mikepenz/release-changelog-builder-action@main
#        with:
#          configuration: 'release-changelog-builder-config.json'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Set env
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/release}" >> $GITHUB_ENV
#
#      - name: Create release
#        id: create_release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release v${{ env.RELEASE_VERSION }}
#          body: ${{steps.build_changelog.outputs.changelog}}
#          draft: false
#          prerelease: false




